export function fetchSnippets() {
    return {
        type: "FETCH_SNIPPETS_FULFILLED",
        payload: {
            snippetData: snippetData
        }
    }
}

export function filterSnippets(searchParams) {
    return {
        type: "FILTER_SNIPPETS",
        payload: {
            snippetData: filterSnippetData(snippetData, searchParams)
        }
    }
}

export function fetchSnippetDetails(id) {
    return {
        type: "FETCH_SNIPPET_DETAILS_FULFILLED",
        payload: {
            snippetDetails: snippetData.filter(person => person.id === id)[0]
        }
    }
}

export function toggleSettingsModal(show, clear) {
    return {
        type: "TOGGLE_SETTINGS_MODAL",
        payload: {
            showSettingsModal: !!show,
            clearSettingsModal: !!clear
        }
    }
}

let filterSnippetData = function(data, searchParams) {
    if(!searchParams || !searchParams[0] || searchParams.length === 0) return data;
    let searchString = searchParams.shift().toLowerCase().trim();
    return filterSnippetData(data.filter(function(obj) {
    return obj.language.toLowerCase().includes(searchString) || 
        obj.title.toLowerCase().includes(searchString) || 
        obj.display.toLowerCase().includes(searchString) || 
        (obj.tags + "").toLowerCase().includes(searchString) ||
        !searchString
    }), searchParams);
};

const snippetData = [
    {"id":1,"title":"Zontrax","display":"neque libero convallis eget eleifend luctus","language":"CSS","tags":["collaboration","Persistent","Object-based","holistic"]},
    {"id":2,"title":"Tampflex","display":"erat vestibulum sed magna at nunc commodo placerat praesent blandit","language":"VB.NET","tags":["focus group","Seamless","mission-critical","Extended","6th generation"]},
    {"id":3,"title":"Bitwolf","display":"ante vel ipsum praesent blandit","language":"HTML","tags":["intermediate","database","application","Operative","help-desk","Open-architected"]},
    {"id":4,"title":"It","display":"sed augue aliquam erat volutpat in congue etiam justo","language":"CSS","tags":["Self-enabling","budgetary management","client-server","parallelism","User-friendly","flexibility","flexibility"]},
    {"id":5,"title":"Namfix","display":"cras in purus eu magna vulputate","language":"VB.NET","tags":["superstructure","Assimilated","hub"]},
    {"id":6,"title":"Duobam","display":"consectetuer adipiscing elit proin interdum mauris","language":"CSS","tags":["Enhanced","value-added","Enterprise-wide","collaboration","array"]},
    {"id":7,"title":"Tin","display":"ante ipsum primis in faucibus orci luctus","language":"JAVASCRIPT","tags":["Stand-alone","Switchable","success","Robust","Grass-roots"]},
    {"id":8,"title":"Temp","display":"quam pede lobortis ligula sit","language":"CSS","tags":["circuit","parallelism","non-volatile","alliance","hierarchy","definition","secondary"]},
    {"id":9,"title":"Hatity","display":"ac leo pellentesque ultrices mattis odio donec vitae nisi","language":"VB.NET","tags":["focus group","moderator","Progressive"]},
    {"id":10,"title":"Konklab","display":"ante ipsum primis in faucibus orci luctus et","language":"VB.NET","tags":["disintermediate","neutral","cohesive","multimedia","Enhanced","internet solution","Upgradable"]},
    {"id":11,"title":"Job","display":"consequat ut nulla sed accumsan felis ut at dolor quis","language":"VB.NET","tags":["zero administration","Enterprise-wide"]},
    {"id":12,"title":"Home Ing","display":"penatibus et magnis dis parturient","language":"HTML","tags":["analyzer","Face to face","protocol","Ergonomic","Managed","reciprocal"]},
    {"id":13,"title":"Transcof","display":"ut nunc vestibulum ante ipsum primis in","language":"VB.NET","tags":["Pre-emptive","background","6th generation"]},
    {"id":14,"title":"Andalax","display":"amet nunc viverra dapibus nulla suscipit ligula","language":"SQL","tags":["eco-centric","framework"]},
    {"id":15,"title":"Bamity","display":"in faucibus orci luctus et ultrices posuere cubilia curae mauris","language":"SQL","tags":["parallelism","Implemented","user-facing","approach","artificial intelligence","Multi-layered"]},
    {"id":16,"title":"Andalax","display":"scelerisque quam turpis adipiscing lorem vitae mattis nibh","language":"CSS","tags":["capability","info-mediaries","capacity","grid-enabled","bi-directional","Streamlined","value-added"]},
    {"id":17,"title":"Y-find","display":"integer non velit donec diam","language":"JAVASCRIPT","tags":["concept","5th generation","Visionary","intangible","Horizontal","human-resource","workforce"]},
    {"id":18,"title":"Fixflex","display":"magnis dis parturient montes nascetur ridiculus mus etiam vel augue","language":"HTML","tags":["exuding","Customer-focused","Progressive","national","logistical","Realigned","toolset"]},
    {"id":19,"title":"Zathin","display":"turpis elementum ligula vehicula consequat morbi a ipsum","language":"HTML","tags":["local","Distributed","bi-directional","process improvement","high-level","secondary"]},
    {"id":20,"title":"Konklab","display":"lacinia eget tincidunt eget tempus vel pede morbi","language":"SQL","tags":["hardware","flexibility","impactful"]},
    {"id":21,"title":"Alpha","display":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum","language":"HTML","tags":["matrices","Re-engineered","incremental","application"]},
    {"id":22,"title":"Biodex","display":"dolor quis odio consequat varius integer ac leo","language":"VB.NET","tags":["algorithm","toolset"]},
    {"id":23,"title":"Stringtough","display":"volutpat quam pede lobortis ligula sit amet","language":"CSS","tags":["regional","attitude-oriented","Advanced","clear-thinking","User-centric","client-driven"]},
    {"id":24,"title":"Zaam-Dox","display":"lacus at turpis donec posuere","language":"VB.NET","tags":["application","interactive","tertiary","national","portal","parallelism"]},
    {"id":25,"title":"Lotlux","display":"est et tempus semper est quam pharetra magna ac consequat","language":"JAVASCRIPT","tags":["Open-source","moratorium","zero tolerance","Business-focused","Total","grid-enabled"]},
    {"id":26,"title":"Viva","display":"etiam justo etiam pretium iaculis justo","language":"SQL","tags":["Multi-lateral","Monitored","Function-based","Implemented","Cross-group"]},
    {"id":27,"title":"Trippledex","display":"orci mauris lacinia sapien quis libero nullam sit amet turpis","language":"VB.NET","tags":["Optional","conglomeration","knowledge user"]},
    {"id":28,"title":"Konklab","display":"rhoncus dui vel sem sed sagittis","language":"HTML","tags":["object-oriented","Secured","Focused"]},
    {"id":29,"title":"Sonsing","display":"rutrum nulla tellus in sagittis dui","language":"CSS","tags":["Synergized","foreground","collaboration","Right-sized","dynamic"]},
    {"id":30,"title":"Stronghold","display":"eu massa donec dapibus duis at velit","language":"CSS","tags":["challenge","analyzer","maximized","Down-sized","help-desk","standardization","array"]},
    {"id":31,"title":"Flexidy","display":"hac habitasse platea dictumst morbi vestibulum velit","language":"SQL","tags":["Total","Managed"]},
    {"id":32,"title":"Mat Lam Tam","display":"potenti in eleifend quam a odio in","language":"HTML","tags":["multimedia","website","Expanded"]},
    {"id":33,"title":"Fix San","display":"non interdum in ante vestibulum ante ipsum primis in faucibus","language":"VB.NET","tags":["structure","flexibility","capability"]},
    {"id":34,"title":"Cardify","display":"nisl nunc nisl duis bibendum","language":"CSS","tags":["client-server","Face to face","info-mediaries","holistic","Robust","Polarised","De-engineered"]},
    {"id":35,"title":"Tresom","display":"integer ac neque duis bibendum morbi non quam nec","language":"CSS","tags":["Inverse","Open-source","Compatible","real-time","alliance","complexity","multimedia"]},
    {"id":36,"title":"Domainer","display":"non velit donec diam neque","language":"SQL","tags":["Optimized","grid-enabled","empowering"]},
    {"id":37,"title":"Bitwolf","display":"auctor sed tristique in tempus sit","language":"CSS","tags":["local area network","Proactive","solution-oriented","scalable"]},
    {"id":38,"title":"Regrant","display":"lacus morbi quis tortor id nulla ultrices aliquet","language":"SQL","tags":["Persistent","moratorium","Secured","Distributed","demand-driven","solution"]},
    {"id":39,"title":"Y-find","display":"hac habitasse platea dictumst aliquam augue quam sollicitudin vitae","language":"SQL","tags":["hub","Multi-tiered","adapter"]},
    {"id":40,"title":"Ronstring","display":"ut rhoncus aliquet pulvinar sed nisl nunc","language":"VB.NET","tags":["functionalities","service-desk"]},
    {"id":41,"title":"Tampflex","display":"aliquet pulvinar sed nisl nunc rhoncus","language":"CSS","tags":["background","info-mediaries"]},
    {"id":42,"title":"Y-find","display":"dolor sit amet consectetuer adipiscing elit proin","language":"HTML","tags":["circuit","encompassing","Assimilated","regional","matrices","Programmable","Open-source"]},
    {"id":43,"title":"Opela","display":"eu est congue elementum in","language":"VB.NET","tags":["adapter","moratorium","parallelism","secured line","Re-contextualized","bandwidth-monitored"]},
    {"id":44,"title":"Zoolab","display":"quam sapien varius ut blandit non interdum","language":"CSS","tags":["system engine","mission-critical","website","Pre-emptive"]},
    {"id":45,"title":"Zoolab","display":"sodales sed tincidunt eu felis fusce posuere felis sed","language":"SQL","tags":["Adaptive","object-oriented","Organized","system-worthy","infrastructure","reciprocal","Graphic Interface"]},
    {"id":46,"title":"Y-find","display":"neque vestibulum eget vulputate ut","language":"HTML","tags":["modular","user-facing","database","collaboration","Sharable"]},
    {"id":47,"title":"Y-Solowarm","display":"ac consequat metus sapien ut nunc","language":"JAVASCRIPT","tags":["Right-sized","local area network"]},
    {"id":48,"title":"Latlux","display":"lorem integer tincidunt ante vel","language":"VB.NET","tags":["Centralized","array","zero administration","scalable"]},
    {"id":49,"title":"Pannier","display":"dis parturient montes nascetur ridiculus mus","language":"CSS","tags":["product","workforce","high-level","Pre-emptive"]},
    {"id":50,"title":"Keylex","display":"turpis adipiscing lorem vitae mattis nibh","language":"SQL","tags":["Universal","foreground","User-friendly","24 hour","high-level","forecast"]},
    {"id":51,"title":"Namfix","display":"tempus vel pede morbi porttitor lorem id ligula suspendisse ornare","language":"JAVASCRIPT","tags":["Compatible","extranet","Future-proofed","Innovative"]},
    {"id":52,"title":"Bamity","display":"est donec odio justo sollicitudin","language":"HTML","tags":["actuating","Profound","internet solution"]},
    {"id":53,"title":"Span","display":"molestie sed justo pellentesque viverra pede","language":"SQL","tags":["zero tolerance","emulation","Pre-emptive","collaboration"]},
    {"id":54,"title":"Flowdesk","display":"tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed","language":"JAVASCRIPT","tags":["local","moderator","asynchronous"]},
    {"id":55,"title":"Treeflex","display":"dui luctus rutrum nulla tellus in","language":"CSS","tags":["paradigm","conglomeration","hub"]},
    {"id":56,"title":"Bamity","display":"curae duis faucibus accumsan odio curabitur convallis duis consequat dui","language":"VB.NET","tags":["zero tolerance","intangible","multimedia","migration","structure"]},
    {"id":57,"title":"Viva","display":"sit amet cursus id turpis integer aliquet massa id","language":"CSS","tags":["solution-oriented","standardization","clear-thinking","Seamless","stable","leverage","composite"]},
    {"id":58,"title":"Tresom","display":"et magnis dis parturient montes nascetur ridiculus mus vivamus","language":"SQL","tags":["project","workforce"]},
    {"id":59,"title":"Bitchip","display":"pharetra magna ac consequat metus sapien","language":"SQL","tags":["array","Cloned","paradigm","Switchable"]},
    {"id":60,"title":"Tin","display":"adipiscing molestie hendrerit at vulputate vitae","language":"CSS","tags":["bandwidth-monitored","Cloned","bottom-line","support"]},
    {"id":61,"title":"Quo Lux","display":"ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices","language":"SQL","tags":["forecast","Diverse"]},
    {"id":62,"title":"Daltfresh","display":"morbi ut odio cras mi pede malesuada","language":"HTML","tags":["algorithm","encoding","Graphical User Interface"]},
    {"id":63,"title":"Subin","display":"purus sit amet nulla quisque arcu","language":"HTML","tags":["Streamlined","Robust","didactic","zero tolerance","Cross-platform","implementation"]},
    {"id":64,"title":"Sonair","display":"tincidunt nulla mollis molestie lorem quisque ut","language":"JAVASCRIPT","tags":["next generation","Reverse-engineered","static","Distributed","actuating","matrix","solution"]},
    {"id":65,"title":"Voltsillam","display":"odio curabitur convallis duis consequat dui nec nisi","language":"VB.NET","tags":["radical","reciprocal","asymmetric","hybrid"]},
    {"id":66,"title":"Bigtax","display":"congue risus semper porta volutpat quam pede lobortis","language":"VB.NET","tags":["mission-critical","Intuitive","user-facing","Integrated","Managed","global","Down-sized"]},
    {"id":67,"title":"Pannier","display":"potenti cras in purus eu magna vulputate luctus cum","language":"JAVASCRIPT","tags":["methodology","holistic","Advanced","local","Right-sized"]},
    {"id":68,"title":"Pannier","display":"metus aenean fermentum donec ut mauris eget","language":"VB.NET","tags":["Re-contextualized","neutral","local area network","secondary","system engine","encompassing","holistic"]},
    {"id":69,"title":"Voltsillam","display":"eu felis fusce posuere felis sed","language":"VB.NET","tags":["4th generation","background","Switchable"]},
    {"id":70,"title":"Quo Lux","display":"ac neque duis bibendum morbi non quam nec","language":"CSS","tags":["circuit","tangible","Down-sized","encoding","dedicated","background"]},
    {"id":71,"title":"Tampflex","display":"dui proin leo odio porttitor id consequat in consequat","language":"HTML","tags":["scalable","Compatible","Multi-lateral","Upgradable","Programmable","Quality-focused","bifurcated"]},
    {"id":72,"title":"Span","display":"ac enim in tempor turpis nec","language":"JAVASCRIPT","tags":["real-time","Front-line","zero tolerance","Horizontal","responsive","Automated","national"]},
    {"id":73,"title":"Namfix","display":"rutrum nulla nunc purus phasellus in felis donec semper","language":"VB.NET","tags":["installation","bottom-line","Visionary","Down-sized","regional","attitude","national"]},
    {"id":74,"title":"Holdlamis","display":"dolor sit amet consectetuer adipiscing elit","language":"HTML","tags":["Function-based","Automated","time-frame","Horizontal","Inverse","3rd generation","hub"]},
    {"id":75,"title":"Treeflex","display":"adipiscing elit proin interdum mauris non","language":"HTML","tags":["forecast","human-resource","even-keeled","Versatile","next generation"]},
    {"id":76,"title":"Pannier","display":"volutpat in congue etiam justo etiam","language":"VB.NET","tags":["extranet","Reverse-engineered","array","logistical","Cross-platform","workforce","tangible"]},
    {"id":77,"title":"Cookley","display":"aenean lectus pellentesque eget nunc","language":"HTML","tags":["moratorium","asynchronous","installation","circuit","coherent","Seamless","Customer-focused"]},
    {"id":78,"title":"Cardify","display":"eget semper rutrum nulla nunc purus phasellus in felis","language":"CSS","tags":["multi-state","transitional","strategy","6th generation","mission-critical","multi-tasking"]},
    {"id":79,"title":"Cookley","display":"sed accumsan felis ut at dolor quis odio consequat","language":"CSS","tags":["Upgradable","full-range","function"]},
    {"id":80,"title":"Tin","display":"nunc rhoncus dui vel sem","language":"VB.NET","tags":["client-server","function","Organic","executive","support","Cross-platform"]},
    {"id":81,"title":"Daltfresh","display":"tempus vivamus in felis eu","language":"SQL","tags":["Enhanced","tertiary"]},
    {"id":82,"title":"Regrant","display":"est congue elementum in hac habitasse platea dictumst morbi","language":"JAVASCRIPT","tags":["analyzer","analyzer","Sharable","system engine"]},
    {"id":83,"title":"Matsoft","display":"adipiscing elit proin risus praesent lectus vestibulum quam sapien","language":"VB.NET","tags":["challenge","incremental"]},
    {"id":84,"title":"Duobam","display":"vestibulum sit amet cursus id","language":"JAVASCRIPT","tags":["infrastructure","heuristic","utilisation","neural-net","zero administration","frame","content-based"]},
    {"id":85,"title":"Biodex","display":"ullamcorper augue a suscipit nulla","language":"CSS","tags":["conglomeration","4th generation","De-engineered"]},
    {"id":86,"title":"Lotstring","display":"diam in magna bibendum imperdiet nullam orci pede venenatis","language":"SQL","tags":["Multi-channelled","stable","Down-sized","analyzing","Configurable"]},
    {"id":87,"title":"Rank","display":"posuere cubilia curae mauris viverra","language":"CSS","tags":["modular","Triple-buffered","stable","Ameliorated","data-warehouse","strategy","Fundamental"]},
    {"id":88,"title":"Veribet","display":"maecenas pulvinar lobortis est phasellus sit","language":"HTML","tags":["info-mediaries","Graphical User Interface","heuristic","info-mediaries","functionalities","Multi-tiered"]},
    {"id":89,"title":"Span","display":"in ante vestibulum ante ipsum primis in faucibus orci","language":"JAVASCRIPT","tags":["info-mediaries","budgetary management","Operative","high-level","parallelism"]},
    {"id":90,"title":"Tempsoft","display":"fusce consequat nulla nisl nunc","language":"JAVASCRIPT","tags":["well-modulated","Programmable","neutral","human-resource","even-keeled"]},
    {"id":91,"title":"Bitchip","display":"potenti cras in purus eu magna vulputate","language":"VB.NET","tags":["Expanded","data-warehouse","Synergistic"]},
    {"id":92,"title":"Stim","display":"nec sem duis aliquam convallis","language":"HTML","tags":["website","multimedia"]},
    {"id":93,"title":"Bitchip","display":"odio justo sollicitudin ut suscipit","language":"JAVASCRIPT","tags":["approach","process improvement","Public-key","coherent","homogeneous","Streamlined"]},
    {"id":94,"title":"Cookley","display":"leo pellentesque ultrices mattis odio donec vitae","language":"HTML","tags":["foreground","Configurable","success"]},
    {"id":95,"title":"Subin","display":"id nulla ultrices aliquet maecenas leo odio condimentum id luctus","language":"JAVASCRIPT","tags":["Seamless","budgetary management","holistic"]},
    {"id":96,"title":"Cookley","display":"erat id mauris vulputate elementum nullam","language":"SQL","tags":["uniform","Profound","data-warehouse","Optimized","Graphic Interface","extranet","Organic"]},
    {"id":97,"title":"Konklab","display":"ac tellus semper interdum mauris ullamcorper purus sit amet","language":"SQL","tags":["Innovative","intermediate","attitude"]},
    {"id":98,"title":"Stringtough","display":"vestibulum ante ipsum primis in","language":"SQL","tags":["Phased","cohesive","coherent","solution-oriented","impactful","human-resource"]},
    {"id":99,"title":"Bitchip","display":"sit amet eros suspendisse accumsan tortor quis turpis","language":"CSS","tags":["adapter","contingency","dynamic"]},
    {"id":100,"title":"Alpha","display":"molestie sed justo pellentesque viverra pede ac","language":"SQL","tags":["model","Universal","Multi-channelled","attitude"]},
    {"id":101,"title":"Andalax","display":"eleifend donec ut dolor morbi","language":"JAVASCRIPT","tags":["Universal","actuating","Multi-tiered","ability","Persevering","local","modular"]},
    {"id":102,"title":"Pannier","display":"vitae nisi nam ultrices libero non mattis","language":"VB.NET","tags":["instruction set","Ergonomic","Multi-lateral","human-resource"]},
    {"id":103,"title":"Lotstring","display":"pretium nisl ut volutpat sapien arcu sed augue aliquam","language":"HTML","tags":["matrix","multi-tasking"]},
    {"id":104,"title":"Ronstring","display":"est lacinia nisi venenatis tristique fusce congue diam id ornare","language":"VB.NET","tags":["well-modulated","attitude","software","implementation"]},
    {"id":105,"title":"Tampflex","display":"congue diam id ornare imperdiet sapien urna pretium","language":"HTML","tags":["budgetary management","database","stable","Persistent","reciprocal"]},
    {"id":106,"title":"Pannier","display":"nec euismod scelerisque quam turpis adipiscing lorem vitae mattis","language":"HTML","tags":["Managed","array","Sharable","transitional","Devolved","Exclusive","core"]},
    {"id":107,"title":"Flowdesk","display":"habitasse platea dictumst aliquam augue","language":"VB.NET","tags":["model","product","cohesive","Compatible","superstructure","Focused","solution"]},
    {"id":108,"title":"Home Ing","display":"nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue","language":"HTML","tags":["methodology","holistic","Innovative","ability","motivating"]},
    {"id":109,"title":"Solarbreeze","display":"quam fringilla rhoncus mauris enim leo rhoncus sed","language":"SQL","tags":["Advanced","groupware","bandwidth-monitored","Enterprise-wide","Multi-lateral"]},
    {"id":110,"title":"Zaam-Dox","display":"cursus vestibulum proin eu mi nulla ac enim","language":"CSS","tags":["Reduced","Diverse","functionalities","Seamless"]},
    {"id":111,"title":"Tin","display":"ante ipsum primis in faucibus orci luctus et","language":"SQL","tags":["Cloned","Open-source","benchmark","Realigned","Polarised"]},
    {"id":112,"title":"Ventosanzap","display":"metus vitae ipsum aliquam non","language":"CSS","tags":["Open-source","Polarised","high-level","Reactive"]},
    {"id":113,"title":"Span","display":"scelerisque mauris sit amet eros suspendisse accumsan tortor quis","language":"JAVASCRIPT","tags":["directional","Virtual"]},
    {"id":114,"title":"Zoolab","display":"curae mauris viverra diam vitae quam","language":"HTML","tags":["matrix","leading edge","paradigm"]},
    {"id":115,"title":"Duobam","display":"quisque ut erat curabitur gravida nisi","language":"SQL","tags":["upward-trending","encompassing","incremental","Upgradable","hardware","Fully-configurable","Upgradable"]},
    {"id":116,"title":"Flexidy","display":"morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl","language":"VB.NET","tags":["regional","bandwidth-monitored","local area network","software"]},
    {"id":117,"title":"Tempsoft","display":"gravida nisi at nibh in hac habitasse platea","language":"VB.NET","tags":["upward-trending","explicit"]},
    {"id":118,"title":"Opela","display":"pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero","language":"JAVASCRIPT","tags":["discrete","Reactive","zero administration"]},
    {"id":119,"title":"Job","display":"leo odio porttitor id consequat in consequat ut nulla sed","language":"SQL","tags":["product","knowledge user","Reactive"]},
    {"id":120,"title":"It","display":"eu mi nulla ac enim","language":"CSS","tags":["empowering","secondary","logistical"]},
    {"id":121,"title":"Ventosanzap","display":"phasellus in felis donec semper","language":"JAVASCRIPT","tags":["knowledge user","User-friendly","Function-based","middleware","knowledge base","local area network"]},
    {"id":122,"title":"Kanlam","display":"ipsum primis in faucibus orci","language":"CSS","tags":["24 hour","Programmable","5th generation","Synchronised","hub","maximized"]},
    {"id":123,"title":"Regrant","display":"in quis justo maecenas rhoncus aliquam","language":"SQL","tags":["budgetary management","infrastructure","Organized","open architecture","regional","time-frame"]},
    {"id":124,"title":"Stringtough","display":"aliquam quis turpis eget elit sodales scelerisque mauris sit","language":"JAVASCRIPT","tags":["productivity","core","policy"]},
    {"id":125,"title":"Voyatouch","display":"diam in magna bibendum imperdiet","language":"HTML","tags":["throughput","neural-net","contingency","human-resource","Polarised","Multi-channelled"]},
    {"id":126,"title":"Bitwolf","display":"sapien placerat ante nulla justo","language":"HTML","tags":["neutral","user-facing"]},
    {"id":127,"title":"Tin","display":"lectus suspendisse potenti in eleifend","language":"VB.NET","tags":["Reduced","Down-sized","Reverse-engineered"]},
    {"id":128,"title":"Tresom","display":"ut ultrices vel augue vestibulum ante","language":"CSS","tags":["global","core","Balanced","Business-focused","empowering"]},
    {"id":129,"title":"Veribet","display":"augue vestibulum ante ipsum primis in faucibus orci luctus","language":"SQL","tags":["needs-based","Optimized"]},
    {"id":130,"title":"Opela","display":"velit vivamus vel nulla eget eros","language":"CSS","tags":["Synergized","stable"]},
    {"id":131,"title":"Matsoft","display":"dapibus duis at velit eu est congue elementum in hac","language":"JAVASCRIPT","tags":["Mandatory","analyzer","Up-sized","open architecture","composite"]},
    {"id":132,"title":"Tres-Zap","display":"dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at","language":"HTML","tags":["attitude","analyzer"]},
    {"id":133,"title":"Flexidy","display":"ligula pellentesque ultrices phasellus id sapien","language":"CSS","tags":["radical","Automated","access","methodology","framework"]},
    {"id":134,"title":"Y-find","display":"eu interdum eu tincidunt in leo maecenas pulvinar","language":"VB.NET","tags":["focus group","standardization","Ameliorated","clear-thinking","algorithm","website","Enterprise-wide"]},
    {"id":135,"title":"Pannier","display":"eros elementum pellentesque quisque porta volutpat erat quisque erat","language":"CSS","tags":["encompassing","zero administration","Right-sized","Business-focused","Fully-configurable","software"]},
    {"id":136,"title":"Konklux","display":"id lobortis convallis tortor risus","language":"VB.NET","tags":["knowledge user","Organic"]},
    {"id":137,"title":"Toughjoyfax","display":"id lobortis convallis tortor risus dapibus augue vel accumsan","language":"SQL","tags":["Implemented","fault-tolerant","infrastructure","stable","Organized","Re-contextualized","matrix"]},
    {"id":138,"title":"Andalax","display":"penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus","language":"CSS","tags":["standardization","support","next generation","Switchable","adapter","modular","Centralized"]},
    {"id":139,"title":"Bytecard","display":"mi in porttitor pede justo eu massa donec","language":"CSS","tags":["neutral","throughput","user-facing","encompassing","motivating"]},
    {"id":140,"title":"Solarbreeze","display":"tellus nulla ut erat id mauris vulputate elementum nullam","language":"SQL","tags":["Inverse","project","instruction set","knowledge user","systemic","Devolved","contingency"]},
    {"id":141,"title":"It","display":"phasellus in felis donec semper sapien a","language":"VB.NET","tags":["implementation","moderator"]},
    {"id":142,"title":"Viva","display":"lacus purus aliquet at feugiat non pretium","language":"JAVASCRIPT","tags":["encoding","5th generation","Multi-layered"]},
    {"id":143,"title":"Sonair","display":"sociis natoque penatibus et magnis dis","language":"SQL","tags":["logistical","Team-oriented","actuating","system-worthy","emulation","methodical","real-time"]},
    {"id":144,"title":"Greenlam","display":"proin leo odio porttitor id consequat in consequat ut nulla","language":"HTML","tags":["zero administration","context-sensitive","motivating"]},
    {"id":145,"title":"Sub-Ex","display":"augue vestibulum ante ipsum primis in faucibus orci luctus et","language":"JAVASCRIPT","tags":["hub","value-added","solution","motivating","Mandatory","scalable","Configurable"]},
    {"id":146,"title":"It","display":"morbi porttitor lorem id ligula suspendisse ornare consequat lectus in","language":"HTML","tags":["reciprocal","Persistent"]},
    {"id":147,"title":"Y-Solowarm","display":"curabitur at ipsum ac tellus semper interdum mauris ullamcorper","language":"SQL","tags":["neutral","monitoring","middleware"]},
    {"id":148,"title":"Lotlux","display":"congue eget semper rutrum nulla nunc purus phasellus","language":"VB.NET","tags":["paradigm","client-driven","national","Devolved","Front-line"]},
    {"id":149,"title":"Voyatouch","display":"tincidunt lacus at velit vivamus vel nulla eget eros","language":"VB.NET","tags":["intermediate","exuding","Programmable"]},
    {"id":150,"title":"Sub-Ex","display":"tincidunt ante vel ipsum praesent blandit","language":"SQL","tags":["Diverse","dedicated","Fundamental","local","portal","Synergistic"]},
    {"id":151,"title":"Pannier","display":"pulvinar nulla pede ullamcorper augue","language":"SQL","tags":["artificial intelligence","secured line"]},
    {"id":152,"title":"Quo Lux","display":"orci mauris lacinia sapien quis libero nullam sit amet","language":"CSS","tags":["time-frame","Extended","contingency","Self-enabling"]},
    {"id":153,"title":"Span","display":"donec vitae nisi nam ultrices libero non mattis pulvinar nulla","language":"VB.NET","tags":["success","content-based","Cloned"]},
    {"id":154,"title":"Toughjoyfax","display":"massa id lobortis convallis tortor risus dapibus","language":"CSS","tags":["multi-state","actuating","asymmetric","modular","capacity"]},
    {"id":155,"title":"Flowdesk","display":"tempus sit amet sem fusce consequat","language":"HTML","tags":["bandwidth-monitored","project","human-resource"]},
    {"id":156,"title":"Fixflex","display":"etiam justo etiam pretium iaculis justo in hac habitasse platea","language":"JAVASCRIPT","tags":["Synergistic","Fundamental","Focused","fresh-thinking","grid-enabled"]},
    {"id":157,"title":"Bitwolf","display":"congue elementum in hac habitasse platea dictumst morbi vestibulum","language":"CSS","tags":["Synergized","Progressive","time-frame"]},
    {"id":158,"title":"Zathin","display":"nisl nunc nisl duis bibendum felis sed interdum venenatis","language":"JAVASCRIPT","tags":["Re-engineered","Realigned","framework","architecture","Object-based"]},
    {"id":159,"title":"Tresom","display":"vel augue vestibulum ante ipsum primis in faucibus orci luctus","language":"VB.NET","tags":["mobile","parallelism","productivity"]},
    {"id":160,"title":"Temp","display":"mi in porttitor pede justo eu massa donec dapibus","language":"VB.NET","tags":["Up-sized","Re-contextualized","Down-sized","array","archive"]},
    {"id":161,"title":"Asoka","display":"at turpis a pede posuere","language":"JAVASCRIPT","tags":["local","transitional"]},
    {"id":162,"title":"Namfix","display":"lacinia nisi venenatis tristique fusce congue diam","language":"SQL","tags":["fault-tolerant","alliance","Polarised","empowering","global","5th generation"]},
    {"id":163,"title":"Regrant","display":"eget tempus vel pede morbi","language":"CSS","tags":["disintermediate","heuristic"]},
    {"id":164,"title":"It","display":"id nisl venenatis lacinia aenean sit amet justo","language":"JAVASCRIPT","tags":["solution","encoding","next generation","Enterprise-wide"]},
    {"id":165,"title":"Zamit","display":"etiam pretium iaculis justo in","language":"SQL","tags":["groupware","client-driven"]},
    {"id":166,"title":"Toughjoyfax","display":"nibh fusce lacus purus aliquet at feugiat non","language":"SQL","tags":["pricing structure","Customizable","Synergized"]},
    {"id":167,"title":"Alphazap","display":"pede venenatis non sodales sed tincidunt eu felis fusce posuere","language":"JAVASCRIPT","tags":["pricing structure","Proactive","attitude-oriented"]},
    {"id":168,"title":"Holdlamis","display":"vivamus in felis eu sapien cursus vestibulum proin eu mi","language":"CSS","tags":["asymmetric","help-desk","even-keeled","Profound","bandwidth-monitored"]},
    {"id":169,"title":"Kanlam","display":"dui vel nisl duis ac nibh fusce","language":"HTML","tags":["composite","Assimilated","optimizing","Streamlined","secured line"]},
    {"id":170,"title":"Zathin","display":"justo morbi ut odio cras","language":"CSS","tags":["methodical","systemic","orchestration"]},
    {"id":171,"title":"Viva","display":"ut ultrices vel augue vestibulum","language":"SQL","tags":["incremental","mobile","initiative","systemic","Multi-lateral","methodology"]},
    {"id":172,"title":"Trippledex","display":"ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque","language":"HTML","tags":["hierarchy","Fully-configurable","Ameliorated","projection","bi-directional"]},
    {"id":173,"title":"Bitchip","display":"quam a odio in hac habitasse platea dictumst maecenas ut","language":"JAVASCRIPT","tags":["empowering","matrices","open architecture","Multi-lateral","Streamlined","empowering","Synergistic"]},
    {"id":174,"title":"Sonair","display":"sed magna at nunc commodo placerat praesent blandit","language":"SQL","tags":["Realigned","model","value-added","system engine","Persistent","eco-centric","Assimilated"]},
    {"id":175,"title":"Veribet","display":"duis aliquam convallis nunc proin at turpis a pede posuere","language":"VB.NET","tags":["open architecture","adapter","zero tolerance","intangible","Monitored","definition","Synchronised"]},
    {"id":176,"title":"Home Ing","display":"rhoncus mauris enim leo rhoncus sed vestibulum sit","language":"CSS","tags":["context-sensitive","object-oriented","system-worthy"]},
    {"id":177,"title":"Pannier","display":"eros vestibulum ac est lacinia nisi venenatis tristique fusce","language":"SQL","tags":["portal","Persevering"]},
    {"id":178,"title":"Treeflex","display":"tempus vel pede morbi porttitor","language":"SQL","tags":["initiative","Seamless","Cross-platform","Graphical User Interface","exuding"]},
    {"id":179,"title":"Cookley","display":"lectus in est risus auctor sed tristique in tempus","language":"JAVASCRIPT","tags":["Innovative","Digitized","hardware","multi-state","stable","function","benchmark"]},
    {"id":180,"title":"Quo Lux","display":"ipsum primis in faucibus orci luctus et","language":"JAVASCRIPT","tags":["responsive","scalable","concept","conglomeration","Reduced","Team-oriented","Ameliorated"]},
    {"id":181,"title":"Andalax","display":"amet eros suspendisse accumsan tortor","language":"CSS","tags":["Extended","alliance","well-modulated","approach","Operative","support","framework"]},
    {"id":182,"title":"Stronghold","display":"maecenas tincidunt lacus at velit vivamus vel","language":"SQL","tags":["project","Focused","dedicated","needs-based"]},
    {"id":183,"title":"Lotstring","display":"id lobortis convallis tortor risus dapibus augue vel","language":"VB.NET","tags":["Exclusive","open system","Assimilated"]},
    {"id":184,"title":"Zoolab","display":"sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit","language":"JAVASCRIPT","tags":["Compatible","groupware","collaboration"]},
    {"id":185,"title":"Biodex","display":"velit nec nisi vulputate nonummy maecenas tincidunt","language":"HTML","tags":["infrastructure","projection","secured line","Automated"]},
    {"id":186,"title":"Zamit","display":"ante ipsum primis in faucibus orci luctus et ultrices","language":"JAVASCRIPT","tags":["Team-oriented","Programmable","internet solution","Grass-roots"]},
    {"id":187,"title":"Zathin","display":"in faucibus orci luctus et ultrices posuere","language":"SQL","tags":["protocol","motivating","User-centric","dedicated"]},
    {"id":188,"title":"Tempsoft","display":"tellus in sagittis dui vel nisl","language":"HTML","tags":["holistic","coherent"]},
    {"id":189,"title":"Gembucket","display":"fermentum justo nec condimentum neque sapien placerat ante nulla","language":"CSS","tags":["Graphical User Interface","projection","stable","Right-sized","Self-enabling","system engine"]},
    {"id":190,"title":"Stim","display":"montes nascetur ridiculus mus etiam vel augue vestibulum rutrum","language":"HTML","tags":["secured line","Open-architected","time-frame","forecast"]},
    {"id":191,"title":"Bigtax","display":"condimentum neque sapien placerat ante nulla justo aliquam","language":"SQL","tags":["middleware","disintermediate","Profound","homogeneous","Profound","installation"]},
    {"id":192,"title":"Pannier","display":"interdum mauris ullamcorper purus sit amet nulla","language":"JAVASCRIPT","tags":["portal","Self-enabling"]},
    {"id":193,"title":"Namfix","display":"id mauris vulputate elementum nullam varius nulla facilisi cras non","language":"JAVASCRIPT","tags":["mobile","utilisation","clear-thinking","Exclusive","Profound","high-level"]},
    {"id":194,"title":"Keylex","display":"luctus nec molestie sed justo pellentesque viverra pede ac diam","language":"VB.NET","tags":["demand-driven","Upgradable","User-centric","functionalities"]},
    {"id":195,"title":"Zontrax","display":"primis in faucibus orci luctus et ultrices","language":"HTML","tags":["Public-key","dedicated","Customer-focused","5th generation"]},
    {"id":196,"title":"Veribet","display":"tincidunt in leo maecenas pulvinar lobortis","language":"VB.NET","tags":["Reactive","firmware","installation","secured line","infrastructure"]},
    {"id":197,"title":"Y-Solowarm","display":"rhoncus aliquet pulvinar sed nisl nunc rhoncus dui","language":"CSS","tags":["maximized","user-facing","client-driven"]},
    {"id":198,"title":"Zathin","display":"sit amet nulla quisque arcu libero rutrum","language":"HTML","tags":["bandwidth-monitored","Robust"]},
    {"id":199,"title":"Toughjoyfax","display":"cum sociis natoque penatibus et","language":"JAVASCRIPT","tags":["Expanded","conglomeration","Organic","complexity"]},
    {"id":200,"title":"Prodder","display":"nullam orci pede venenatis non sodales sed tincidunt","language":"VB.NET","tags":["systematic","Distributed","systemic","initiative"]},
    {"id":201,"title":"Keylex","display":"congue eget semper rutrum nulla","language":"VB.NET","tags":["Ameliorated","Monitored","Multi-channelled","Enhanced","software"]},
    {"id":202,"title":"Vagram","display":"mauris eget massa tempor convallis nulla","language":"JAVASCRIPT","tags":["initiative","interactive","project","internet solution","zero administration","Upgradable"]},
    {"id":203,"title":"Trippledex","display":"justo eu massa donec dapibus duis","language":"HTML","tags":["Cloned","open system","task-force","customer loyalty","time-frame","didactic","core"]},
    {"id":204,"title":"Mat Lam Tam","display":"sit amet eleifend pede libero quis","language":"CSS","tags":["User-centric","Networked","model","mission-critical","explicit","Profit-focused"]},
    {"id":205,"title":"Solarbreeze","display":"ac leo pellentesque ultrices mattis","language":"JAVASCRIPT","tags":["circuit","Streamlined","Right-sized"]},
    {"id":206,"title":"Veribet","display":"aliquam quis turpis eget elit sodales scelerisque mauris sit","language":"CSS","tags":["contextually-based","Open-architected","asynchronous","zero tolerance","object-oriented","Enhanced","data-warehouse"]},
    {"id":207,"title":"Quo Lux","display":"dis parturient montes nascetur ridiculus mus etiam vel augue","language":"CSS","tags":["concept","Graphical User Interface","Diverse","Streamlined","zero administration","Profound"]},
    {"id":208,"title":"Asoka","display":"fusce lacus purus aliquet at feugiat non pretium","language":"HTML","tags":["infrastructure","Ergonomic","systematic","Graphic Interface","Reverse-engineered","methodical"]},
    {"id":209,"title":"Alpha","display":"pulvinar nulla pede ullamcorper augue a suscipit nulla elit","language":"VB.NET","tags":["monitoring","standardization"]},
    {"id":210,"title":"Mat Lam Tam","display":"pellentesque at nulla suspendisse potenti cras in purus eu","language":"CSS","tags":["Vision-oriented","regional","structure","hybrid","Cross-platform","24/7"]},
    {"id":211,"title":"Home Ing","display":"dapibus duis at velit eu est congue","language":"VB.NET","tags":["adapter","Total","neutral","task-force"]},
    {"id":212,"title":"Job","display":"morbi vel lectus in quam fringilla rhoncus","language":"CSS","tags":["Robust","Synergistic","toolset","stable","hardware"]},
    {"id":213,"title":"Andalax","display":"sit amet nulla quisque arcu libero rutrum ac lobortis","language":"HTML","tags":["Down-sized","Fundamental","capacity"]},
    {"id":214,"title":"Duobam","display":"platea dictumst morbi vestibulum velit","language":"JAVASCRIPT","tags":["encryption","Enterprise-wide"]},
    {"id":215,"title":"Bitchip","display":"primis in faucibus orci luctus et ultrices posuere","language":"JAVASCRIPT","tags":["array","conglomeration","Inverse","Mandatory","complexity","Reactive","User-friendly"]},
    {"id":216,"title":"Transcof","display":"donec semper sapien a libero nam","language":"SQL","tags":["Realigned","fault-tolerant","next generation","groupware","grid-enabled","uniform","Fundamental"]},
    {"id":217,"title":"Tampflex","display":"at diam nam tristique tortor","language":"JAVASCRIPT","tags":["Profit-focused","modular","maximized","holistic","workforce"]},
    {"id":218,"title":"Regrant","display":"nunc viverra dapibus nulla suscipit ligula in lacus","language":"SQL","tags":["User-centric","encryption","Graphical User Interface","functionalities","time-frame"]},
    {"id":219,"title":"Veribet","display":"donec odio justo sollicitudin ut suscipit","language":"SQL","tags":["knowledge base","maximized","Persevering"]},
    {"id":220,"title":"Latlux","display":"morbi porttitor lorem id ligula","language":"VB.NET","tags":["definition","Persistent","approach"]},
    {"id":221,"title":"Stringtough","display":"tortor quis turpis sed ante vivamus","language":"CSS","tags":["Cloned","Multi-channelled","Stand-alone"]},
    {"id":222,"title":"Cardguard","display":"enim blandit mi in porttitor pede justo","language":"VB.NET","tags":["conglomeration","implementation","throughput","asynchronous"]},
    {"id":223,"title":"Lotlux","display":"vestibulum vestibulum ante ipsum primis in faucibus orci luctus","language":"VB.NET","tags":["fresh-thinking","stable","Ergonomic","Optimized","migration","Implemented"]},
    {"id":224,"title":"Zamit","display":"pede malesuada in imperdiet et","language":"HTML","tags":["optimal","superstructure","Digitized","6th generation","moratorium","responsive","Exclusive"]},
    {"id":225,"title":"Home Ing","display":"nulla nunc purus phasellus in felis donec semper sapien a","language":"VB.NET","tags":["Optimized","Reactive"]},
    {"id":226,"title":"Lotlux","display":"id ligula suspendisse ornare consequat","language":"JAVASCRIPT","tags":["Devolved","moratorium","even-keeled","Multi-channelled","Vision-oriented","client-driven","functionalities"]},
    {"id":227,"title":"Job","display":"varius nulla facilisi cras non velit","language":"CSS","tags":["Visionary","Front-line"]},
    {"id":228,"title":"Biodex","display":"neque libero convallis eget eleifend","language":"JAVASCRIPT","tags":["matrices","5th generation","implementation","Devolved","capacity","forecast"]},
    {"id":229,"title":"Flexidy","display":"non velit donec diam neque vestibulum eget","language":"VB.NET","tags":["Robust","Reduced","Multi-lateral","structure","Streamlined","optimal"]},
    {"id":230,"title":"Keylex","display":"quam sapien varius ut blandit non","language":"CSS","tags":["scalable","regional"]},
    {"id":231,"title":"Konklux","display":"convallis eget eleifend luctus ultricies eu nibh","language":"JAVASCRIPT","tags":["Right-sized","moderator","throughput","optimal","Centralized","circuit"]},
    {"id":232,"title":"Tresom","display":"vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis","language":"VB.NET","tags":["reciprocal","reciprocal"]},
    {"id":233,"title":"Aerified","display":"posuere felis sed lacus morbi sem mauris laoreet ut rhoncus","language":"VB.NET","tags":["capability","Digitized","matrix","executive","responsive"]},
    {"id":234,"title":"Ventosanzap","display":"eu nibh quisque id justo sit amet sapien dignissim","language":"SQL","tags":["leading edge","Optional","encryption"]},
    {"id":235,"title":"Konklux","display":"vivamus metus arcu adipiscing molestie hendrerit","language":"SQL","tags":["Reactive","Realigned","zero administration","mission-critical","Phased","initiative"]},
    {"id":236,"title":"Zontrax","display":"lobortis ligula sit amet eleifend pede libero","language":"CSS","tags":["asynchronous","Down-sized","upward-trending","synergy","Public-key","foreground","Polarised"]},
    {"id":237,"title":"Gembucket","display":"consequat in consequat ut nulla sed accumsan felis ut","language":"SQL","tags":["collaboration","help-desk","Down-sized","Team-oriented","service-desk"]},
    {"id":238,"title":"Aerified","display":"egestas metus aenean fermentum donec ut mauris eget","language":"SQL","tags":["Assimilated","stable","Ameliorated"]},
    {"id":239,"title":"Transcof","display":"nisl nunc rhoncus dui vel sem sed sagittis nam","language":"CSS","tags":["encoding","contingency","function","mission-critical","content-based","zero administration","Stand-alone"]},
    {"id":240,"title":"Holdlamis","display":"lacus morbi quis tortor id nulla ultrices aliquet","language":"CSS","tags":["application","composite","ability","project","Total","Organized"]},
    {"id":241,"title":"Tampflex","display":"justo sollicitudin ut suscipit a feugiat","language":"VB.NET","tags":["encompassing","hub","alliance","dedicated"]},
    {"id":242,"title":"Fixflex","display":"maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus","language":"VB.NET","tags":["secured line","intranet"]},
    {"id":243,"title":"Sub-Ex","display":"vestibulum eget vulputate ut ultrices vel augue vestibulum","language":"SQL","tags":["analyzer","open architecture","middleware","Pre-emptive","needs-based","Ameliorated"]},
    {"id":244,"title":"Bigtax","display":"molestie lorem quisque ut erat curabitur gravida nisi","language":"SQL","tags":["Business-focused","full-range","toolset","Open-source"]},
    {"id":245,"title":"Tempsoft","display":"convallis morbi odio odio elementum eu interdum eu","language":"JAVASCRIPT","tags":["Enhanced","utilisation","needs-based","non-volatile","Intuitive","hierarchy","info-mediaries"]},
    {"id":246,"title":"Alphazap","display":"nisi volutpat eleifend donec ut","language":"VB.NET","tags":["impactful","Profound","Centralized","Vision-oriented"]},
    {"id":247,"title":"Viva","display":"pulvinar sed nisl nunc rhoncus dui vel sem sed","language":"SQL","tags":["eco-centric","Operative"]},
    {"id":248,"title":"Solarbreeze","display":"luctus et ultrices posuere cubilia curae duis","language":"SQL","tags":["Diverse","matrix","needs-based","Monitored","Intuitive","Function-based","De-engineered"]},
    {"id":249,"title":"Y-Solowarm","display":"dolor sit amet consectetuer adipiscing elit","language":"HTML","tags":["web-enabled","secured line"]},
    {"id":250,"title":"Lotstring","display":"morbi non lectus aliquam sit amet diam in","language":"CSS","tags":["Decentralized","high-level"]}
];